---
# template: 1.5.0
name: "Lint/ShellCheck"

env:
  DEV_CICD_DEBUG: ${{ vars.DEV_CICD_DEBUG || 'NONE' }}
  DEV_CICD_DEBUG_BASH: ${{ vars.DEV_CICD_DEBUG_BASH || '' }}
  BL64_LIB_CICD: ${{ vars.BL64_LIB_CICD || 'YES' }}

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
      - "release/**"
    paths:
      - "src/**"

jobs:
  lint-shellcheck:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Cache base tools"
        uses: "actions/cache@v5"
        with:
          path: |
            ./lib/bl64
            ./lib/inst64
          key: "dev-tools"

      - name: "Cache module tools"
        uses: "actions/cache@v5"
        with:
          path: |
            ./lib/shellcheck
          key: "dev-shellcheck"

      - name: "Download tools"
        run: |
          ./bin/dev-lib-base &&
          ./bin/dev-lib-shellcheck

      - name: "Run Linter"
        run: "./bin/dev-lint-shellcheck"

      - name: "Save report as repository artifact"
        uses: actions/upload-artifact@v6
        continue-on-error: true
        if: always()
        with:
          name: "shellcheck-lint.json"
          path: "./logs/shellcheck/shellcheck-lint.json"
...
